### ISSUE TITLE
Runbook List Nil Pointer Error

### ISSUE THREAD

**Issue by awil897** [OctopusDeploy/cli#243]
## The bug

Error when attempting to list available runbooks in a Project.

## Command to reproduce

Identical error when specifying the Space or Project or using interactively
```
octopus -s SpaceName runbook list --project 'Project Name'
octopus -s SpaceName runbook list 
octopus runbook list
```

## Outcome

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xdfca65]

goroutine 1 [running]:
github.com/OctopusDeploy/cli/pkg/cmd/runbook/list.listRun(0xc000476900, {0x10bf448?, 0xc0003dc3c0}, 0xc000008798)
        /home/runner/work/cli/cli/pkg/cmd/runbook/list/list.go:120 +0x465
github.com/OctopusDeploy/cli/pkg/cmd/runbook/list.NewCmdList.func1(0xc000476900?, {0xc000096a00?, 0x2?, 0x2?})
        /home/runner/work/cli/cli/pkg/cmd/runbook/list/list.go:57 +0x73
github.com/spf13/cobra.(*Command).execute(0xc000476900, {0xc0000969e0, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc00039ac00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
        /home/runner/work/cli/cli/cmd/octopus/main.go:73 +0x465
```

## Versions

**cli**:1.3.0

**Octopus Server**:2021.1.7665

**Comment by benPearce1** [comment]
We can't make any guarantees about the CLI operating against an older version.

Can you check the response you get by navigating in your browser to `https://server/api/{spaceId}/projects/{projectId}/runbooks`? 

The space id can be obtained easily from existing URLs, the project Id is not shown in the url and will be need to be obtained via the developer console network tab.

**Comment by benPearce1** [comment]
Unable to recreate the issue, no response from original poster
